### PR TITLE
React plot migration

### PR DESCRIPTION
**Pull request by cheekw**
#130 #135 #138 
- migrate components of plotly to react
- added dynamic select components implementation
- added use of react-based chaise components
- added support for multiple charts
- added support for multiple types of plots in a chart
- added support for fetch select changes and non-fetch select changes
- added parallelism in requests for initial fetch for filling selector data

may need to revisit templateParams
may need to look at the use of noData hack

### CODE REVIEW

**Review by jrchudy — CHANGES_REQUESTED** [review]
From reviewing the UI functionality, I found some issues that need to be addressed before we can merge this pull request.

For violin plot:
 - [x] The gene selector looks disabled when it is NOT disabled
 - [x] When `Study` is in the url, the study selector should not be shown
    - check the issue #135  for more info. The study information for the specified study should still be fetched in case it's used for templating
  - [ ] When `NCBI_GeneID` is in the url, the gene selector should be disabled with the rowname of the gene from the url displayed
    - check the issue #135  for more info
    - input should be simple with no button and greyed out
  - [ ] When `Study` or `NCBI_GeneID` or both are present in the url, have a link in the top right corner to go to violin plot with no `Study` or `NCBI_GeneID` url parameters
  - [ ] `xaxis.group_keys[x].title_display_pattern` displays for the x axis title properly but this is also included in the group by dropdown display. In that case it's not being templated and showing as a raw string like `[Experiment](/chaise/recordset/#2/RNASeq:Experiment)`
    - we should not be showing this in the dropdown
    - ```
       group_keys: [
         {
           column_name: "Experiment",
           title_display_pattern: "[Experiment](/chaise/recordset/#2/RNASeq:Experiment)",
           ...                     
         }, ...
         ```
    - think about how this can be addressed and we will have to talk about what solution is best
  - [x] `graphic_link_pattern` doesn't work for violin plot
  
  
For plot app in general:
 - [ ] when the page is resized, the app should be responsive
   - when I open the browser console in the old version of the app, the plot shrinks to make sure the content can be shown in the visible part of the viewport
 - [x] `disable_default_legend_click` doesn't seem to be implemented
   - This attribute should be used to allow for turning off the default click functionality of the legend.
   - this default functionality should not be turned off just because there is a link defined, we want the config property to control this

**Comment by cheekw** [comment]
Following fixes/changes were added:

Selectors:
- Study Selector gone when in URL
- NCBI_GeneID Selector gone when in URL
- fixed gene selector looking disabled

Violin Graphic Click:
- fixed violin graphic links, clickable on the violin plot.

Layout responsive behavior:
- absolute min width x height = 800 x 600, 
- responsive behavior VP smaller than given layout but bigger than min

Legend Click:
- fixed disable_default_legend_click

**Comment by RFSH** [comment]
@cheekw I updated Chaise to the issues that I observed in plot app, so I pushed a change to this branch to use it. It should solve the race condition that we were seeing on recordset modal (the terminal error that sometimes happened). 

While testing I found two issues that I think you should address:
- In dev mode, React is complaining about usage of `button` inside another `button`. 
- In prod mode, I'm seeing duplicated catalog and schema requests to the server (In dev mode you will see 4).  This can happen if you're sending some requests in `useEffect` and aren't guarding against doing it only once.  See if you can what's triggering these requests and make sure all of your `useEffect`s are only called once. The catalog and schema requests are done as part of "introspection". So they could be triggered by `ERMrest.resolve` which is most probably what you're doing. `AppWrapper` is also calling the catalog request on load.

**Comment by cheekw** [comment]
> @cheekw I updated Chaise to solved the issues that I observed in plot app, and pushed a change to this branch to use the new version of Chaise. It should solve the race condition that we were seeing on recordset modal (the terminal error that sometimes happened).
> 
> While testing I found two issues that I think you should address:
> 
> * In dev mode, React is complaining about usage of `button` inside another `button`.
> * In prod mode, I'm seeing duplicated catalog and schema requests to the server (In dev mode you will see 4).  This can happen if you're sending some requests in `useEffect` and aren't guarding against doing it only once.  See if you can find what's triggering these requests and make sure all of your `useEffect`s are only called once. The catalog and schema requests are done as part of "introspection". So they could be triggered by `ERMrest.resolve` which is most probably what you're doing. `AppWrapper` is also calling the catalog request on load.

- Button inside a button occurs because I have wrapped the disabled dropdown of the gene selector to disable the dropdown behavior and "mimic" a button. While this is usually bad practice, I think it could be fine here since the buttons inside are not active. It also saves time of building a "fake dropdown component"
- Multiple requests:
If you look closely at the request uri are different for the first 3. The 4th one was a bug that I just fixed and pushed.
Request 1: For Gene Selector (using resolve())
Request 2: For Study Selector (using resolve())
Request 3: The actual plot data (using http.get())
Request 4: (bug that has been fixed in the recent commit, it was doing an extra fetch on clicking a selector)

There maybe a way to bundle request 1,2,3 together. I haven't looked into if this was possible though. Requests 1 and 2 should be occurring in parallel to save time. 3 should be waiting on 1 and 2.

**Comment by jrchudy** [comment]
I updated my above comment with checkboxes to track which tasks are complete. After reviewing the UI again, looks like most of the concerns have been fixed. The gene selector was changed but not fixed properly and 2 other things were not addressed (listed in above comment).

The issue (#135) describes how the app is supposed to behave when 1 of `Study` or `NCBIGene_ID` are present in the URL, when both are present, and neither are present.

No url parameters:
 - https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin
 - show both selectors active

Both `Study` and `NCBIGene_ID`:
 - https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&Study=14-3PXT&NCBI_GeneID=1
 - show both selectors active
 - show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right

Only `Study`:
 - https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&Study=14-3PXT
 - hide study selector
 - show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right
 
Only `NCBIGene_ID`:
 - https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&&NCBI_GeneID=1
 - disable gene selector
 - show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right

**Review by jrchudy — COMMENTED** [review]
Code changes look good. Please address the other minor issues I mentioned and we can finalize the code review to merge these changes.

Regarding the button in button that you mentioned in the other comment, we have a similar implementation in chaise, that can be found [here](https://github.com/informatics-isi-edu/chaise/blob/master/src/components/input-switch/foreignkey-field.tsx#L206-L235). We have a div marked as a `chaise-input-group` which is a wrapper we made for bootstrap's `input-group`. This input group includes the input (actually a div) and the button. The click event is on the input group in this case.

**Comment by cheekw** [comment]
> I updated my above comment with checkboxes to track which tasks are complete. After reviewing the UI again, looks like most of the concerns have been fixed. The gene selector was changed but not fixed properly and 2 other things were not addressed (listed in above comment).
> 
> The issue (#135) describes how the app is supposed to behave when 1 of `Study` or `NCBIGene_ID` are present in the URL, when both are present, and neither are present.
> 
> No url parameters:
> 
> * https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin
> * show both selectors active
> 
> Both `Study` and `NCBIGene_ID`:
> 
> * https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&Study=14-3PXT&NCBI_GeneID=1
> * show both selectors active
> * show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right
> 
> Only `Study`:
> 
> * https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&Study=14-3PXT
> * hide study selector
> * show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right
> 
> Only `NCBIGene_ID`:
> 
> * https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin&&NCBI_GeneID=1
> * disable gene selector
> * show `[Visualization with Gene & Study selectors](https://staging.gudmap.org/deriva-webapps/plot/?config=study-violin)` link in top right

@jrchudy 
- behavior updated to be the same

**Comment by cheekw** [comment]
added
- title in groupby object and used that instead to fix the issue with dropdown with display_patterns `xaxis.group_keys[x].title`

**Comment by jrchudy** [comment]
2 issues still: 
1. The case when both `Study` and `NCBIGene_ID` are in the url, both selectors should be **visible AND active**. 
image
The older implementation looks like this:
image

2. The way gene selector is being disabled still makes the input look like it is enabled with a slightly darker grey background.
image
The older implementation looks more like this with a darker background and the button is not shown:
image

**Comment by cheekw** [comment]
> 2 issues still:
> 
> 1. The case when both `Study` and `NCBIGene_ID` are in the url, both selectors should be **visible AND active**.
> 
> image
> 
> The older implementation looks like this:
> image
> 
> 2. The way gene selector is being disabled still makes the input look like it is enabled with a slightly darker grey background.
> 
> image
> 
> The older implementation looks more like this with a darker background and the button is not shown:
> image

Thanks for the catches.
- behavior logic: if all requestable selectors with href are on, they are now all active
- disabled styling is made to be consistent with the image shown above.

**Review by jrchudy — APPROVED** [review]

**Pull request merged**
